### ISSUE TITLE
Asset Changes not detected by Spock

### ISSUE THREAD

**Issue by PhilJ** [statamic/spock#34] opened 2019-01-30 13:11 UTC
I can confirm the issue reported by Waze: 

Spock is not getting notified about asset changes and is therefore not able to commit them. We also added an manual workaround similary to @wanze. 

However, sSince this is throwing errors on every failed commit it would be great if this could be fixed. We are using Statamic `2.11.5`and Spock `2.1.0`.

_Originally posted by @wanze in https://github.com/statamic/spock/issues/24#issuecomment-447334083_ :
 
I am also running into this issue using the following setup:

 * Statamic `2.11.3`
 * Spock `2.1.0`

Ignored events:
```
  - Statamic\Events\Data\AssetUploaded
  - Statamic\Events\Data\AssetMoved
  - Statamic\Events\Data\AssetDeleted
  - Statamic\Events\Data\FileUploaded
```

My current solution is to use a custom after command:
```
- if (( $(git status -s | wc -l) > 0 )); then git add --all && git commit -m "[skip-ci] Additional changes after running Spock" && git push; fi
```

**Comment by jesseleite** [comment] 2019-06-19 18:21
Sorry for the delay.  Hmm, I couldn't reproduce @wanze's issue either.  How is your asset container configured?

**Comment by goldnead** [comment] 2020-03-30 14:03
Sorry for not responding since then. Our Issue got resolved somehow. With Statamic `2.11.3` and Spock `2.2.2` those Events get properly handled. You can close this Issue npw :)

**Closed** 2020-03-30 14:06 UTC
